[package]
name = "assert"
version = "0.2.3"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/assert"
homepage = "https://github.com/stainless-steel/assert"
documentation = "https://stainless-steel.github.io/assert"
description = "The package provides assertions for testing."
